# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 741)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 741))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 741))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TrainUser = QtWidgets.QPushButton(self.centralwidget)
        self.TrainUser.setGeometry(QtCore.QRect(970, 350, 141, 51))
        self.TrainUser.setObjectName("TrainUser")
        self.selectImgBtn = QtWidgets.QPushButton(self.centralwidget)
        self.selectImgBtn.setGeometry(QtCore.QRect(970, 190, 141, 51))
        self.selectImgBtn.setObjectName("selectImgBtn")
        self.msgBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.msgBrowser.setGeometry(QtCore.QRect(30, 580, 800, 60))
        self.msgBrowser.setMinimumSize(QtCore.QSize(800, 60))
        self.msgBrowser.setMaximumSize(QtCore.QSize(800, 60))
        self.msgBrowser.setObjectName("msgBrowser")
        self.cameraBtn = QtWidgets.QPushButton(self.centralwidget)
        self.cameraBtn.setGeometry(QtCore.QRect(970, 120, 141, 51))
        self.cameraBtn.setObjectName("cameraBtn")
        self.recordBtn = QtWidgets.QPushButton(self.centralwidget)
        self.recordBtn.setGeometry(QtCore.QRect(970, 50, 141, 51))
        self.recordBtn.setObjectName("recordBtn")
        self.TrainPub = QtWidgets.QPushButton(self.centralwidget)
        self.TrainPub.setGeometry(QtCore.QRect(970, 430, 141, 51))
        self.TrainPub.setObjectName("TrainPub")
        self.selectVidBtn = QtWidgets.QPushButton(self.centralwidget)
        self.selectVidBtn.setGeometry(QtCore.QRect(970, 270, 141, 51))
        self.selectVidBtn.setObjectName("selectVidBtn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(860, 560, 81, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(860, 610, 81, 31))
        self.label_2.setObjectName("label_2")
        self.idEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.idEdit.setGeometry(QtCore.QRect(960, 560, 151, 31))
        self.idEdit.setObjectName("idEdit")
        self.nameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nameEdit.setGeometry(QtCore.QRect(960, 610, 151, 31))
        self.nameEdit.setObjectName("nameEdit")
        self.showLabel = QtWidgets.QLabel(self.centralwidget)
        self.showLabel.setGeometry(QtCore.QRect(30, 50, 800, 500))
        self.showLabel.setMinimumSize(QtCore.QSize(800, 500))
        self.showLabel.setMaximumSize(QtCore.QSize(800, 500))
        self.showLabel.setText("")
        self.showLabel.setObjectName("showLabel")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(850, 650, 93, 28))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TrainUser.setText(_translate("MainWindow", "User Train"))
        self.selectImgBtn.setText(_translate("MainWindow", "Select Images"))
        self.cameraBtn.setText(_translate("MainWindow", "Open Camera"))
        self.recordBtn.setText(_translate("MainWindow", "Record Face"))
        self.TrainPub.setText(_translate("MainWindow", "Pub Train"))
        self.selectVidBtn.setText(_translate("MainWindow", "Select Videos"))
        self.label.setText(_translate("MainWindow", "User ID"))
        self.label_2.setText(_translate("MainWindow", "User Name"))
        self.pushButton.setText(_translate("MainWindow", "Commite"))
        self.menu.setTitle(_translate("MainWindow", "可选择录入人脸并训练或选择一张图片或一段视频来进行识别"))
